<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup>
		<Description>
			SQLite-based implementation of the dotRMDY.DataStorage.Abstractions package.
		</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\dotRMDY.DataStorage.Abstractions\dotRMDY.DataStorage.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="sqlite-net-pcl" Version="1.11.285" />
	</ItemGroup>

</Project>
